Request to merge Feature style
kimothokamau/awesomebooks pull request #4
Opened 2021-07-07 20:25 UTC by Jmagero

-  Add CSS styles to the application to make it match this wireframe:

2021-07-07 23:14 UTC, umararshadbut requested changes
Hi @Jmagero and @kimothokamau , 

Good job so far :+1:!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- **[OPTIONAL]** Please create an assets directory and move the JavaScript and CSS files into the assets.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
HAPPY CODING :computer:
**Umair Arshad**

2021-07-07 23:14 UTC, umararshadbut commented on style.css
> +  width: 80%; */
**[REQUIRED]** Please remove the commented code.

2021-07-08 09:45 UTC, kimothokamau commented
- Removed commented code
- Put css and js files in assets folder

2021-07-08 09:48 UTC, carlos-ssh approved these changes
Hi @kimothokamau & @Jmagero, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-13 20:35 UTC, merged